- allow long long comparisons in perl swig code, enable perl bindings
Swig is boldly enabling long long on ix86 and x32 and then comparing
that no smaller types, which causes gcc to protest against such practices.

dnf5-5.2.10.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx: In function ‘int SWIG_AsVal_long_SS_long(SV*, long long int*)’:
dnf5-5.2.10.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx:2236:36: error: comparison is always true due to limited range of data type [-Werror=type-limits]
 2236 |     if (UVSIZE < sizeof(*val) || v < LLONG_MAX) {
      |                                    ^
dnf5-5.2.10.0/build/bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx:2243:56: error: comparison is always true due to limited range of data type [-Werror=type-limits]
 2243 |     if (IVSIZE <= sizeof(*val) || (v >= LLONG_MIN && v <= LLONG_MAX)) {
      |                                                        ^
cc1plus: all warnings being treated as errors
make[2]: *** [bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/build.make:79: bindings/perl5/libdnf5/CMakeFiles/perl5_common.dir/CMakeFiles/perl5_common.dir/commonPERL_wrap.cxx.o] Error 1